
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - relationships:
              to: ref('my_first_dbt_model')
              field: id

  - name: snowflake_customer_purchases
    description: "This is a model of customer and their purchases"
    columns:
      - name: C_CUSTKEY
        description: "Key of customer"
        tests:
          - unique
          - not_null   
          
  - name: cumulative_orders_by_date
    description: "This is a model of customer and their purchases"
    columns:
      - name: o_orderdate
        description: "Key of customer"
  
  - name: dates
    description: "this is a incremental table"

  - name: playing_with_tests
    description: "this is a testing table"
    columns:
      - name: C_CUSTKEY
        description: "Key of customer"
        tests:
          - unique
          - not_null 
      - name: C_MKTSEGMENT
        tests:
          - accepted_values:
              values: ['BUILDING', 'AUTOMOBILE', 'MACHINERY', 'HOUSEHOLD','FURNITURE']
    